# -*- mode: ruby -*-
# vi: set ft=ruby :

# Maquina virtual con SO usado en los computadores del laboratorio con que se
# evalua el proyecto

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "box-cutter/fedora21"

end
